FROM --platform=linux/amd64 ubuntu:20.04 as builder

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y meson pkg-config libz-dev libjansson-dev libssl-dev ninja-build gcc

COPY . /repo
WORKDIR /repo/build
RUN meson ..
RUN ninja

FROM ubuntu:20.04 as package
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y libjansson-dev libssl-dev
COPY --from=builder /repo/build/cmd/jose /
COPY --from=builder /repo/build/lib /deps
ENV LD_LIBRARY_PATH=/deps
